---
title: "analysis_reliability_check_with_R"
author: "Jelena Meyer"
format: html
editor: visual
---

## Recalculate Reliability of all scales using Cronbach's Alpha from `psych`

```{r packages,  echo=TRUE, eval=TRUE, results='hide', warning=FALSE, message=FALSE}
library(readr)
library(psych)
library(tidyverse)
library(dplyr)
library(tidyr)
```



```{r read-data, echo=TRUE, eval=TRUE, results='hide'}
items_per_LLM <- read_csv("processed_data/items_per_llm.csv", show_col_types = FALSE)
```



```{r subset-data}
SSSV_subscale_df <- items_per_LLM %>%
  filter(category == "SSbor")
  #filter(experiment == "FTND scale")

SSSV_subscale_wide <- SSSV_subscale_df %>%
  pivot_wider(
    id_cols = c(experiment, model),
    names_from = item,
    values_from = score
  )

```




```{r}
# Compute reliability -> with check keys (turn item orientation around again)
psych::alpha(SSSV_subscale_wide %>% select(-experiment, -model), check.keys = TRUE)
```


```{r}
# Compute reliability -> without check keys (keep items as is)
psych::alpha(SSSV_subscale_wide %>% select(-experiment, -model), check.keys = FALSE)
```






